import fs from 'fs';
import path from 'path';

/**
 * Generates the .limrun/ workspace companion for `lim xcode rbe`: a Bazel
 * package pinning the remote fleet's Xcode version and an rc fragment with the
 * remote-execution flags under the `limrun` config. The caller learns the
 * fleet's version key from the instance's RBE status, so the generated config
 * always matches the fleet without any user action; rerunning the command
 * after a fleet Xcode upgrade regenerates the pin.
 */

export const LIMRUN_DIR = '.limrun';
export const TRY_IMPORT_LINE = 'try-import %workspace%/.limrun/bazelrc';
const TRY_IMPORT_COMMENT = '# Added by lim xcode rbe: loads the generated remote-execution config.';

/**
 * Renders the generated Bazel package pinning the remote Xcode version.
 * versionKey is the fleet's `xcodebuild -version` in major.minor.patch.build
 * form (e.g. 26.4.0.17E192); the SDK default is its major.minor prefix.
 */
export function renderXcodeConfigBuild(versionKey: string): string {
  const parts = versionKey.split('.');
  if (parts.length < 3) {
    throw new Error(`unexpected Xcode version key from the instance: ${versionKey}`);
  }
  const sdk = `${parts[0]}.${parts[1]}`;
  const shortAlias = `${parts[0]}.${parts[1]}`;
  const fullAlias = `${parts[0]}.${parts[1]}.${parts[2]}`;
  return `# Generated by lim xcode rbe. Do not edit; rerun the command to refresh.
#
# Pins the Xcode version Bazel declares for remote actions to the limrun
# fleet's Xcode, independent of the Xcode installed on this machine. Selected
# via the generated .limrun/bazelrc (--config=limrun).
xcode_version(
    name = "remote_xcode",
    aliases = [
        "${shortAlias}",
        "${fullAlias}",
    ],
    default_ios_sdk_version = "${sdk}",
    default_macos_sdk_version = "${sdk}",
    default_tvos_sdk_version = "${sdk}",
    default_watchos_sdk_version = "${sdk}",
    version = "${versionKey}",
)

xcode_config(
    name = "remote_xcode_config",
    default = ":remote_xcode",
    versions = [":remote_xcode"],
)
`;
}

/** Renders the rc fragment with the remote-execution flags under --config=limrun. */
export function renderLimrunBazelrc(port: number): string {
  return `# Generated by lim xcode rbe. Do not edit; rerun the command to refresh.
build:limrun --remote_executor=grpc://127.0.0.1:${port}
build:limrun --remote_default_exec_properties=OSFamily=Darwin
build:limrun --spawn_strategy=remote
build:limrun --noremote_local_fallback
build:limrun --xcode_version_config=//.limrun:remote_xcode_config
build:limrun --action_env=PATH=/usr/bin:/bin
`;
}

/**
 * Idempotently ensures the workspace .bazelrc try-imports the generated
 * fragment. Creates .bazelrc when missing. Returns true when the file changed.
 */
export function ensureTryImport(workspaceDir: string): boolean {
  const bazelrcPath = path.join(workspaceDir, '.bazelrc');
  let current = '';
  if (fs.existsSync(bazelrcPath)) {
    current = fs.readFileSync(bazelrcPath, 'utf8');
    if (current.includes(TRY_IMPORT_LINE)) {
      return false;
    }
  }
  const block = `${TRY_IMPORT_COMMENT}\n${TRY_IMPORT_LINE}\n`;
  const next = current === '' ? block : `${current.replace(/\n*$/, '\n\n')}${block}`;
  fs.writeFileSync(bazelrcPath, next);
  return true;
}

export type RbeWorkspaceFiles = {
  buildFile: string;
  bazelrcFragment: string;
  bazelrcUpdated: boolean;
};

/**
 * Writes .limrun/{BUILD,bazelrc,.gitignore} into the workspace and wires the
 * try-import. The .gitignore containing "*" makes the directory self-ignoring
 * so nothing else in the user's repo needs to change.
 */
export function writeRbeWorkspaceFiles(
  workspaceDir: string,
  xcodeVersionKey: string,
  port: number,
): RbeWorkspaceFiles {
  const dir = path.join(workspaceDir, LIMRUN_DIR);
  fs.mkdirSync(dir, { recursive: true });
  const buildFile = path.join(dir, 'BUILD');
  const bazelrcFragment = path.join(dir, 'bazelrc');
  fs.writeFileSync(buildFile, renderXcodeConfigBuild(xcodeVersionKey));
  fs.writeFileSync(bazelrcFragment, renderLimrunBazelrc(port));
  fs.writeFileSync(path.join(dir, '.gitignore'), '*\n');
  const bazelrcUpdated = ensureTryImport(workspaceDir);
  return { buildFile, bazelrcFragment, bazelrcUpdated };
}
