// Generated by scripts/generate-telemetry-config.mjs during release builds.
// Empty values keep local and unconfigured builds fail-open/no-op.
export const DEFAULT_POSTHOG_PROJECT_KEY = '';
export const DEFAULT_POSTHOG_HOST = 'https://l.limrun.com';
