#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${ROOT}/native/build"
WASM_OUT="${OUT_DIR}/xdelta3-stream.wasm"
EMCC="${EMCC:-emcc}"

if ! command -v "${EMCC}" >/dev/null 2>&1; then
  echo "emcc not found. Install/activate emsdk, or set EMCC=/path/to/emcc." >&2
  exit 1
fi

mkdir -p "${OUT_DIR}" "${ROOT}/src"

"${EMCC}" \
  -O3 \
  -std=gnu17 \
  -I"${ROOT}/native/xdelta/xdelta3" \
  -DREGRESSION_TEST=0 \
  -DXD3_USE_LARGESIZET=0 \
  -DXD3_USE_LARGEFILE64=0 \
  -DSIZEOF_SIZE_T=4 \
  -DEXTERNAL_COMPRESSION=0 \
  -DVCDIFF_TOOLS=0 \
  -s STANDALONE_WASM \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s INITIAL_MEMORY=33554432 \
  -s MAXIMUM_MEMORY=536870912 \
  -s EXPORTED_FUNCTIONS="['_malloc','_free','_xd3w_new','_xd3w_free','_xd3w_input_buf','_xd3w_input_cap','_xd3w_avail_input','_xd3w_step','_xd3w_output_ptr','_xd3w_output_len','_xd3w_consume_output','_xd3w_source_ptr','_xd3w_source_request_offset','_xd3w_source_request_len','_xd3w_provide_source','_xd3w_close','_xd3w_errmsg']" \
  --no-entry \
  "${ROOT}/native/xdelta/xdelta3/xdelta3.c" \
  "${ROOT}/native/xd3w.c" \
  -o "${WASM_OUT}"

node - "${WASM_OUT}" "${ROOT}/src/wasm-embedded.ts" <<'NODE'
const fs = require('fs');
const [wasmPath, outPath] = process.argv.slice(2);
const base64 = fs.readFileSync(wasmPath).toString('base64');
const chunks = base64.match(/.{1,100}/g) || [];
const body = [
  '// Generated by native/build.sh. Do not edit by hand.',
  'export const xdelta3WasmBase64 =',
  ...chunks.map((chunk, index) => `  '${chunk}'${index === chunks.length - 1 ? ';' : ' +'}`),
  '',
].join('\n');
fs.writeFileSync(outPath, body);
NODE

echo "Wrote ${WASM_OUT}"
echo "Wrote ${ROOT}/src/wasm-embedded.ts"
